Traceback (most recent call last):
  File "/var/www/venv/bin/daphne", line 8, in <module>
    sys.exit(CommandLineInterface.entrypoint())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/venv/lib/python3.12/site-packages/daphne/cli.py", line 171, in entrypoint
    cls().run(sys.argv[1:])
  File "/var/www/venv/lib/python3.12/site-packages/daphne/cli.py", line 233, in run
    application = import_by_path(args.application)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/venv/lib/python3.12/site-packages/daphne/utils.py", line 17, in import_by_path
    target = importlib.import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/var/www/app/app/asgi.py", line 18, in <module>
    from worker.routing import ws_urlpatterns
  File "/var/www/app/worker/routing.py", line 3, in <module>
    from .consumers import VideoConsumer, TaskTransferConsumer
  File "/var/www/app/worker/consumers.py", line 13, in <module>
    from master.databaseWork import DatabaseWork
  File "/var/www/app/master/databaseWork.py", line 1, in <module>
    from .models import *
  File "/var/www/app/master/models.py", line 6, in <module>
    class Access_app(models.Model):  
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/venv/lib/python3.12/site-packages/django/db/models/base.py", line 129, in __new__
    app_config = apps.get_containing_app_config(module)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/venv/lib/python3.12/site-packages/django/apps/registry.py", line 260, in get_containing_app_config
    self.check_apps_ready()
  File "/var/www/venv/lib/python3.12/site-packages/django/apps/registry.py", line 137, in check_apps_ready
    settings.INSTALLED_APPS
  File "/var/www/venv/lib/python3.12/site-packages/django/conf/__init__.py", line 81, in __getattr__
    self._setup(name)
  File "/var/www/venv/lib/python3.12/site-packages/django/conf/__init__.py", line 61, in _setup
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Requested setting INSTALLED_APPS, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
